import { Geist, Geist_Mono } from "next/font/google";
import "./global.scss";
import Clock from "@/components/clock/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="wrapper">
          <div className="navbar">
            <div className="title">
              <h1>TITLE PAGE</h1>
            </div>
            <div className="time">
              <Clock />
            </div>
          </div>
          <div className="main-content">{children}</div>
          <div className="footer">Footer</div>
        </div>
      </body>
    </html>
  );
}
